name: "Publish docker image"
description: "Pushes build artifacts to DockerHub"
inputs:
  registry-username:
    description: 'Username for image registry'
    required: true
  registry-password:
    description: 'Password for image registry'
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: docker build -t "${DOCKERHUB_IMAGE_NAME}:latest" -t "${DOCKERHUB_IMAGE_NAME}:${GITHUB_SHA::8}" ./target

    - shell: bash
      run: docker login -u ${{inputs.registry-username}} -p ${{inputs.registry-password}}

    - shell: bash
      run: docker push --all-tags "${GITHUB_REPOSITORY_OWNER,,}/${REPOSITORY_NAME}"
